import { defineConfig } from 'vitest/config'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  resolve: {
    // Native tsconfig paths resolution (Vite 6+) — no plugin needed
    tsconfigPaths: true,
  },
  test: {
    globals: true,
    setupFiles: ['./vitest.setup.ts'],
    projects: [
      {
        // ─── Unit tests: domain + application logic ────────────────────────
        // Pure TypeScript — NO DOM needed. Fast, isolated, no browser APIs.
        extends: true,
        test: {
          name: 'unit',
          environment: 'node',
          include: [
            '__tests__/unit/**/*.{test,spec}.{ts,tsx}',
            '__tests__/core/**/*.{test,spec}.{ts,tsx}',
            'src/core/**/*.{test,spec}.{ts,tsx}',
          ],
        },
      },
      {
        // ─── Integration tests: React components, pages ────────────────────
        // Needs DOM. Covers UI behavior with Testing Library.
        extends: true,
        test: {
          name: 'integration',
          environment: 'jsdom',
          include: ['__tests__/integration/**/*.{test,spec}.{ts,tsx}'],
        },
      },
    ],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'lcov', 'html'],
      include: ['src/core/**/*.{ts,tsx}'],
      exclude: [
        'node_modules/**',
        '.next/**',
        '**/*.config.{ts,mts,js,mjs}',
        '**/*.d.ts',
        'vitest.setup.ts',
        // Generated by Supabase CLI — not our code
        'src/core/shared/infrastructure/supabase/database.types.ts',
        // Thin wrappers with zero logic — only delegate to third-party libs
        'src/core/shared/infrastructure/theme/ThemeProvider.tsx',
        'src/core/shared/infrastructure/swr/SWRProvider.tsx',
        'src/core/shared/infrastructure/supabase/server.ts',
        // UI components that are pure rendering — tested indirectly via hooks/integration
        'src/core/shared/infrastructure/theme/ThemeToggle.tsx',
        'src/core/shared/infrastructure/i18n/LocaleSwitcher.tsx',
        'src/core/users/infrastructure/components/UserList.tsx',
        // useUsers hook — tested in integration tests with SWR wrapper
        'src/core/users/infrastructure/hooks/useUsers.ts',
        // Logger singletons — thin one-liner wrappers (createLogger is tested)
        'src/core/shared/infrastructure/logger/serverLogger.ts',
        'src/core/shared/infrastructure/logger/clientLogger.ts',
        'src/core/shared/infrastructure/logger/index.ts',
      ],
      thresholds: {
        lines: 80,
        functions: 80,
        branches: 80,
        statements: 80,
      },
    },
  },
})
