import { defineConfig, globalIgnores } from 'eslint/config'
import nextVitals from 'eslint-config-next/core-web-vitals'
import nextTs from 'eslint-config-next/typescript'
import prettierConfig from 'eslint-config-prettier'

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  prettierConfig,
  // eslint-plugin-react@7.x uses context.getFilename() which was removed in
  // ESLint v10. Setting an explicit version string avoids the detection code
  // path that calls the removed API.
  {
    settings: {
      react: {
        version: '19',
      },
    },
  },
  // ─── no-console: error ───────────────────────────────────────────────
  // Prevents accidental console.log / console.info / etc. in source code.
  // Use the Logger (serverLogger / clientLogger) instead.
  // If you REALLY need a console call (e.g. inside ConsoleLogger adapter),
  // disable per-line: // eslint-disable-next-line no-console
  {
    rules: {
      'no-console': 'error',
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
    // Generated by vitest coverage
    'coverage/**',
  ]),
])

export default eslintConfig
